name: Terraform CI/CD Pipeline for Deploying AWS Resources

on:
    push:
        branches:
            - "main"

env:
    AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    build-infra:
        name: Terraform CI/CD
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Terraform Init
              run: terraform init
              working-directory: ./terraform-VPC

            - name: Terraform Validate
              run: terraform validate
              working-directory: ./terraform-VPC

            - name: Terraform Plan
              run: terraform plan
              working-directory: ./terraform-VPC

            - name: Terraform Apply
              run: terraform destroy --auto-approve
              working-directory: ./terraform-VPC
